name: Maven Build

on: 
  pull_request:
  workflow_dispatch:

jobs:
  run:
    uses: zepben/.github/.github/workflows/maven-build.yml@main
    with:
      private: false
      license_check: true
    secrets: inherit

